server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/migrations/master.xml

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto

app:
  rabbitmq:
    exchange: order.exchange
    queue: order.created
    routing-key: order.created